[logging]
level = "INFO"
encoding = "utf-8"
format = "%(asctime)s %(levelname)s:%(message)s"
datefmt = "%Y-%m-%dT%I:%M:%S"

[flow_event]
ignore_fields = [ ]
ignore_risks = [ ]
flow_event_name = [ "update", "end", "idle", "detected", "detection-update" ]
filename = "flow_event"

  [flow_event.geoip2_city]
  enabled = false
  filepath = "/tmp/city.mmdb"
  keys = [ "country.names.en", "location" ]

[daemon_event]
ignore_fields = [ ]
daemon_event_name = [ "init", "status" ]
filename = "daemon_event"

[packet_event]
ignore_fields = [ ]
packet_event_name = [ "packet-flow" ]
filename = "packet_event"

[error_event]
ignore_fields = [ ]
error_event_name = [ "error-flow" ]
filename = "error_event"
