version: "3.9"
services:
  consumer:
    image: stefan96/heidpi:consumer-latest
    volumes:
      - ${PWD}/heidpi-data:/var/log/
    network_mode: host
    depends_on:
      - producer
  producer:
    image: stefan96/heidpi:producer-latest
    network_mode: host
