version: "3.9"
services:
  consumer:
    image: stefan96/heistream-ndpid:consumer-latest
    volumes:
      - ${PWD}/heistream-data:/var/log/
    network_mode: host
    depends_on:
      - producer
  producer:
    image: stefan96/heistream-ndpid:producer-latest
    network_mode: host
