name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Producer Image
      run: docker build . --file Dockerfile.producer --tag stefan96/heistream-ndpid:latest --tag stefan96/heistream-ndpid:producer-latest

    - name: Build Consumer Image
      run: docker build . --file Dockerfile.consumer --tag stefan96/heistream-ndpid:consumer-latest
