name: Docker Publisch CI

on:
  schedule:
    - cron: '45 8 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build Producer Image
      run: docker build . --file Dockerfile.producer --tag stefan96/heidpi-producer:${{ steps.meta.outputs.tags }}

    - name: Build Consumer Image
      run: docker build . --file Dockerfile.consumer --tag stefan96/heidpi-consumer:${{ steps.meta.outputs.tags }}

    - name: Docker Push
      run: |
        docker push stefan96/heidpi-producer:${{ steps.meta.outputs.tags }}
        docker push stefan96/heidpi-consumer:${{ steps.meta.outputs.tags }}

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: stefan96/heidpi
        short-description: ${{ github.event.repository.description }}